[package]
authors = ["Rakshith Ravi <rakshith.ravi@gmx.com>"]
edition = "2018"
name = "gotham"
version = "0.1.0"

[dependencies]
async-std = "1.4.0"
serde_json = "*"
async-trait = "0.1.24"
futures = "0.3.4"
futures-util = "0.3.4"
